### ISSUE TITLE
Errors when running --configure

### ISSUE THREAD

**Issue by AxelFP** [tvgrabbers/tvgrabnlpy#32] opened 2015-06-17 19:43 UTC
I get the following error when running 'tv_grab_nl.py --configure':

  File "/usr/bin/perlbin/vendor/tv_grab_nl.py", line 783
    self.teveblad_genericnames = {"ochtend- en dagprogramma's", \
(The problem lies at the comma, before the slash)

I'm using python 2.6:
Python 2.6.6 (r266:84292, Nov 18 2011, 05:12:23)
[GCC 4.5.1] on linux2

I tried v2.1.7 and v2.1.9-beta of the script.

**Comment by hikavdh** [comment] 2015-06-17 19:54
This is very common syntax. The backslash is an escape to negate the linebreak. This is old code, being there since 2.0.0. So the problem is in something on your system.  
I suggest upgrading Python to 2.7.9 or there about. 2.6.6 is old.

**Comment by AxelFP** [comment] 2015-06-18 07:35
Ok I'll try to update to 2.7.

Btw: I read the following in the FAQ, which made me believe 2.6.6 shouldn't be a problem: "Op dit moment met versies 2.6 en 2.7".

**Comment by hikavdh** [comment] 2015-06-18 07:39
It's just that this line never gave a problem and shouldn't. I can not think of anything else, or are you running in msWindows? Because that is totally untested.

**Comment by hikavdh** [comment] 2015-06-18 09:14
One other possibility comes to mind. Do you use the utf-8 codeset? Because if not, especially if it is not even on your machine, that can give all kind of weird problems.

**Comment by hikavdh** [comment] 2015-06-18 09:22
I looked further. And it looks like your system breaks its neck over the backslash, which again makes me suspect you're running on msWindows. The backslash escape is on all kind of places in the code, so ...

**Comment by AxelFP** [comment] 2015-06-18 13:47
Thanks for the thoughts!
I'm running on Arch Linux (LinHES R7.4).
The python error points to the comma, so I don't think it's the slash.
UTF-8 codeset? euh, good question, I'll investigate that.

**Comment by hikavdh** [comment] 2015-06-18 15:51
Python errors normally point at something after the error, so then it's in the text. But this is just the initial variable declaration. Very basic. The only thing different from earlier declarations is that, because of the single quote in the text, I use double quotes. But that still is all basic. But maybe this isn't in 2.6.6 or else it's an utf-8 thing. You having that old Python version says it's also an old distribution.  
By the way on the mythtv list somebody gave up on archlinux because basic stuff wouldn't work. Broken packages?

**Comment by AxelFP** [comment] 2015-06-19 07:00
Maybe it has something to do with the variable type not being known in 2.6.6?
I'll try to install 2.7.10 and see what happens.

LinHES uses it's own repositories per version. So I'm not able to upgrade to anything higher than 2.6.6  automatically.

I've build 2.7.10 from source code already, but I don't want to break my system. As I'm not really familiar with python: Do you know how to run a script with python 2.7.10 without installing it first?

**Comment by winfried** [comment] 2015-06-19 07:34
This is caused by a python 2.6 / 2.7 issue. Up to python 2.6 curly brackets would only define dictionaries. Since python 2.7 curly brackets can be used to define a set, if you use a "," as separator or a dictonary if you use a ":" as separator. So in python 2.7 a = {'a', 'b'} would create a set, in python 2.6 that would raise an error. To be complete:

Python 2.7.10 (default, Jun  1 2015, 16:21:46) 
>>> a = {'a', 'b'}
>>> type(a)
<type 'set'>
>>> b = {'a': 'b'}
>>> type(b)
<type 'dict'>
>>> c = ('a', 'b')
>>> type(c)
<type 'tuple'>

I guess it is a typo in the kind of brackets used.

**Comment by AxelFP** [comment] 2015-06-19 07:47
Do I understand I right if I say that when the c type definition is used it would work for python 2.7 and 2.6?

**Comment by winfried** [comment] 2015-06-19 08:55
Yes, that should work

**Comment by hikavdh** [comment] 2015-06-20 09:36
You're right. All the other declarations are dicts and this should be a tuple. I never noticed, because it just worked. A set is OK, because it is a unique list, but I meant a list or tuple.
Obviously nobody before used Python 2.6, for as said this line is there since 2.0.0. Iĺl change it and it will be in the next release. I will also check for similar occasions.

**Comment by hikavdh** [comment] 2015-06-20 09:54
Added new release: https://github.com/tvgrabbers/tvgrabnlpy/releases/tag/beta-2.1.9-p20150620 
Let me know if it works!

**Comment by AxelFP** [comment] 2015-06-20 18:49
Yes that worked!
Unfortunately it stumbles over something else now:
----------
Creating config file: /root/.xmltv/tv_grab_nl_py.conf

An unexpected error has occured at line: 8703, 9: expected path separator ([)
                   tracing back to line: 1756, 534
                   tracing back to line: 1626, 471
                   tracing back to line: 6010, 153
                   tracing back to line: 198, 6
                   tracing back to line: 176, 39
                   tracing back to line: 93, 285
----------

**Comment by hikavdh** [comment] 2015-06-20 19:18
As far as I can see, this means the grabber is not going to work with your version. It stumbles over syntax in the elementtree module, that is used to examine the webpages. It looks like your version doesn't allow attribute definition in an html tag path ('div[@class="section"]'). It wants a path separator '/' and it finds an attribute definition starting with a '['. This is used on multiple places.

**Comment by hikavdh** [comment] 2015-06-20 19:27
Theoretically I probably could rewrite, but I have no way to test. 2.6 is not anymore in the Gentoo emerge tree. And as said earlier your version is old, so upgrading is sensible.

**Comment by AxelFP** [comment] 2015-06-20 19:50
Fair enough, I'll try to upgrade.
But then please remove the stated 2.6 compatibility in the FAQ and in the script, so it's clear to anyone it won't work.

**Comment by hikavdh** [comment] 2015-06-20 19:56
I just did and I'll update the version test in the code!

**Closed** 2015-06-20 20:07 UTC
Labels: wontfix
